### PR TITLE
attempt to clarify use of the word Concepts

### LINKED ISSUE #62: Clarity for "Concepts"
In the text description of Concepts, it says to use the following terms, but the concept of "Concept" hasn't really been introduced.  By inference it seems we are saying that Concept is a generic term for verbs, activity types, and attachment usage types.

### PR DESCRIPTION
**Pull request by fugu13**
Closes #62

### CODE REVIEW

**Comment by jhaag75** [comment]
I think mentioning that the "Concepts" term was also borrowed from SKOS for representing / organizing knowledge might also be helpful or clarify. 

I received quite a bit of positive feedback that the vocabulary spec's introductory RDF info and "alignment with SKOS explanation" was very helpful. I highly recommend we have similar sections in the profile spec. Or perhaps just reuse some of what was written for the vocab spec and incorporate it into the profile spec (replace "vocabulary datasets" with "profiles"). We could easily just deprecate the vocab spec and redirect it to the profile spec, but we also need an introduction explaining the changes and shift, and the improvements. 

https://adl.gitbooks.io/companion-specification-for-xapi-vocabularies/content/dataset_schema_design/alignment_with_skos.html

**Comment by fugu13** [comment]
Will add SKOS reference before merge

**Comment by fugu13** [comment]
Also, quick review for minor grammar issues

**Comment by fugu13** [comment]
Will be merged after above addressed

**Comment by fugu13** [comment]
Issues, addressed, merging

**Pull request merged**
