### PR TITLE
add StatementRefs. Closes #39 and #99.

### LINKED ISSUE #39: alignments and statement references sections need tidy up
I'd be inclined to delete both because I don't know what alignments are and I don't see why statement references need special treatment.

### PR DESCRIPTION
**Pull request by fugu13**
This makes it possible to, for example, have a StatementTemplate for "reviewing accomplishment" statements where the actor reviews an object agent, then have another StatementTemplate for "has been judged competent in" statements that must have a context statement StatementRef pointing at "reviewing accomplishment" statements.

Also includes a variety of other clarifying language related to this change, some of which should be reviewed for inclusion if this PR is rejected.

### CODE REVIEW

**Comment by FeLungs** [comment]
+1, "If the referenced Statement is available to the checking system, it MUST be checked for matching the given Statement Template, but if it is not, it MUST be assumed to match the given Statement Template. If all the rules are fulfilled, and the StatementRefs check out, then the statement matches the template." 

I like this change, seems like the logical way to check statements with StatementRefs against Statement Templates

**Comment by fugu13** [comment]
Consensus: merge, evaluate as the whole spec gets looked at

**Comment by garemoko** [comment]
"the Learning Record Provider MUST make it the UUID of a Statement matching at least one of the specified Statement Templates."

Does the referenced statement then have to be received by the LRS before the referencing statement? What if they come in a batch? What about paging via more links? 

I'd be inclined to make this a SHOULD as very difficult to validate unless it's made over restrictive.

**Comment by fugu13** [comment]
@garemoko agreed on difficulty of validating, which is why the behavior of the LRP is a MUST, but the validating system is given this language:

> Additionally, check if the object StatementRef and context StatementRef requirements are met. If the referenced Statement is available to the checking system, it MUST be checked for matching the given Statement Template, but if it is not, it MUST be assumed to match the given Statement Template.

**Pull request merged**
